FROM osrf/ros:melodic-desktop-full

SHELL ["/bin/bash", "-c"]

RUN apt update && apt install libspdlog-dev -y && apt install gdb -y

#get ouster lib
COPY ../ouster-ros/ /catkin_ws/src/ouster_ros/


WORKDIR /catkin_ws
RUN source /opt/ros/melodic/setup.bash \
    && catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release  
# -BUILD_PCAP=True

RUN echo "source devel/setup.bash" >> ~/.bashrc


#docker build . --file LIO-EKF/docker/Dockerfile_ouster  -t thesis_ouster
#roslaunch ouster_ros replay.launch