common:
    lidar_topic:  "/ouster/points"
    imu_topic:  "/imu/data"
    laser_up_topic: "/mavros/distance_sensor/up"

lidar:
    deskew: true
    preprocess: true
    max_range: 300.0 
    min_range: 0.8
    max_points_per_voxl: 30
    voxel_size: 0.15
    max_iteration: 70

imu:
    # IMU noise parameters
    arw: [2, 2, 2]          # [deg/sqrt(hr)]
    vrw: [40, 40, 40]          # [m/s/sqrt(hr)]
    gbstd: [200.0, 200.0, 200.0]        # [deg/hr]
    abstd: [500.0, 500.0, 500.0]     # [mGal]
    corrtime: 1.0                    # [hr]

lio:
    # initial position std, north, east and down in n-frame. [m, m, m]
    initposstd: [ 0.00, 0.00, 0.00 ]
    # initial velocity std, north, east and down speed in n-frame. [m/s, m/s, m/s]
    initvelstd: [ 0.00, 0.00, 0.00 ]
    # initial attitude std, roll, pitch and yaw std. [deg, deg, deg]
    initattstd: [ 0.0, 0.0, 0.0 ]

    extrinsic_T: [-0.023, 0.000,-0.023]
    extrinsic_R: [  0.9656520,  0.0000000,  0.2598390,
   0.0000000,  1.0000000,  0.0000000,
  -0.2598390,  0.0000000,  0.9656520 ]
    #transform the imu frame to front-right-down (which is used in the code)
    imu_tran_R: [  1,0,0,
    0,-1,0,
    0,0,-1 ]
    # imu_tran_R: [ 0.7071068,0,-0.7071068,
    #           0,-1,0,
    #           -0.7071068,  0,  -0.7071068]

                 